### PR TITLE
Add bs-containers-core

### PR DESCRIPTION
**Pull request by cxa**

### CODE REVIEW

**Comment by glennsl** [comment]
Hi! I'm a bit hesitant to promote an alternative std lib, at least without properly managing expectations. And I'd rather try to get bs-containers to a state where alternatives aren't needed. What's the use case for this?

cc @dorafmon

**Comment by ghost** [comment]
Agree with @glennsl, probably we should focus on getting bs-containers ready?

**Comment by cxa** [comment]
You are right. Maybe I'll transfer to bs-containers when it's ready,  but I need one that can be used in production currently.

**Comment by glennsl** [comment]
That's understandable. Thanks!

**Pull request closed without merging**
