### PR TITLE
Add bs-glamor

### PR DESCRIPTION
**Pull request by poeschko**
(Full disclosure: I just created bs-glamor.)

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks. This looks good! But could you move it to the Bindings/Frontend section? (Reglamor is under Libraries because it's supposed to be a reimplementation)

**Comment by poeschko** [comment]
Absolutely! Sorry I missed that. I moved it.

**Comment by poeschko** [comment]
BTW, do you prefer a link to a personal repo like I have now, or are you interested in moving it into the https://github.com/BuckleTypes org?

**Comment by glennsl** [comment]
That's really up to you and how you want to balance responsibility and credit. It's more likely to be adopted, and perhaps even discovered, in BuckleTypes of course. I'd be happy to create a repo for you if you want to move it over.

**Comment by poeschko** [comment]
Cool, thanks! I'll think about it, but let's leave it as-is for now.

**Comment by glennsl** [comment]
Sure thing!

**Pull request merged**
